thoth-station/slo-reporter

openshift/cronJob-template.yaml

Use a specific token for slo-reporter (thanos-token to retrieve metrics longer than 12h)

Use thanos secret

---

app.py
thoth/slo_reporter/sli_report.py

Add environment to distinguish metrics

Add environment to distinguish metrics

---

thoth/slo_reporter/sli_learning.py
thoth/slo_reporter/sli_report.py

Add Solver info and Environment Info

Add solver info and environment info

---

.zuul.yaml

updated zuul config file
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

updated zuul config file

---

app.py
thoth/slo_reporter/sli_knowledge_graph.py
thoth/slo_reporter/sli_learning.py
thoth/slo_reporter/sli_pypi_knowledge_graph.py

Remove int

---

README.md
thoth/slo_reporter/sli_kebechet.py
thoth/slo_reporter/sli_report.py
thoth/slo_reporter/sli_template.py
thoth/slo_reporter/static/templates/thoth_kebechet.html

Updated documentation and Added Kebechet SLI report. 
Closes #15 
Related #20 
Sample HTML Generated -

Add kebechet SLI report

---

README.md
openshift/buildConfig-template.yaml
openshift/cronJob-template.yaml
openshift/imageStream-template.yaml

Add API version in Openshift template

Add apiVersion

---

README.md
thoth/slo_reporter/configuration.py
thoth/slo_reporter/sli_kebechet.py
thoth/slo_reporter/sli_references.py
thoth/slo_reporter/static/templates/thoth_kebechet.html
thoth/slo_reporter/static/templates/thoth_references.html

Add Thoth reports references

---

app.py
openshift/cronJob-template.yaml
thoth/slo_reporter/configuration.py
thoth/slo_reporter/sli_kebechet.py
thoth/slo_reporter/sli_knowledge_graph.py
thoth/slo_reporter/sli_learning.py
thoth/slo_reporter/sli_pypi_knowledge_graph.py
thoth/slo_reporter/sli_user_api.py
thoth/slo_reporter/sli_workflow_quality.py

Related-To: https://github.com/thoth-station/metrics-exporter/pull/405
- Add env variables
- Modify query for workflows
- Introduce error for not retrieved metrics

Modify query workflows

---

openshift/cronJob-template.yaml

Modify time of run of the cronjob

Change time

---

thoth/slo_reporter/static/templates/thoth_service_quality.html

correct variable due to wrong rebase

---

app.py
thoth/slo_reporter/configuration.py

Reduce spams
Add check on day of the week to decide when to send email.

Add day of week check to send emails

---

thoth/slo_reporter/configuration.py
thoth/slo_reporter/sli_learning.py

- Add security workflow to SLI
- Use delta for new solvers SLI

Add SLI for security workflow

---

thoth/slo_reporter/sli_learning.py

Update evaluation method

---

Pipfile
Pipfile.lock
app.py
thoth/slo_reporter/__init__.py
thoth/slo_reporter/configuration.py
thoth/slo_reporter/sli_base.py
thoth/slo_reporter/sli_kebechet.py
thoth/slo_reporter/sli_knowledge_graph.py
thoth/slo_reporter/sli_learning.py
thoth/slo_reporter/sli_pypi_knowledge_graph.py
thoth/slo_reporter/sli_references.py
thoth/slo_reporter/sli_report.py
thoth/slo_reporter/sli_template.py
thoth/slo_reporter/sli_thoth_integration.py
thoth/slo_reporter/sli_user_api.py
thoth/slo_reporter/sli_workflow_latency.py
thoth/slo_reporter/sli_workflow_quality.py
thoth/slo_reporter/static/templates/thoth_integrations.html
thoth/slo_reporter/utils.py

Fixes: https://github.com/thoth-station/slo-reporter/issues/81
Add Thoth Integrations to Thoth SLI so that we can share this info with others and see results in Superset

Add thoth integrations and introduce generalization for files stored in Ceph

---

README.md
thoth/slo_reporter/sli_apis/README.md
thoth/slo_reporter/sli_knowledge_graph/README.md
thoth/slo_reporter/sli_learning/README.md
thoth/slo_reporter/sli_python_knowledge_graph/README.md
thoth/slo_reporter/sli_thoth_integrations/README.md
thoth/slo_reporter/sli_thoth_services/README.md

Adjust links to READMEs and images

---

thoth/slo_reporter/sli_knowledge_graph/README.md

remove duplicate .png from link

---

thoth/slo_reporter/sli_learning/README.md
thoth/slo_reporter/sli_learning/sli_learning.py

Fixes: https://github.com/thoth-station/slo-reporter/issues/82
Add SI learning rate and SI analyzed packages SLI

Add SLI for Security-Indicator

---

app.py
thoth/slo_reporter/sli_apis/sli_user_api.py
thoth/slo_reporter/sli_backends/sli_workflow_latency.py
thoth/slo_reporter/sli_backends/sli_workflow_quality.py
thoth/slo_reporter/sli_backends/sli_workflow_task_quality.py
thoth/slo_reporter/sli_base.py
thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
thoth/slo_reporter/sli_learning/sli_learning.py
thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py
thoth/slo_reporter/sli_report.py
thoth/slo_reporter/sli_thoth_integrations/sli_thoth_integration.py
thoth/slo_reporter/sli_thoth_services/sli_kebechet.py

Add CSV file columns and make sure we store with correct values.

Add sli columns check

---

app.py

reset time to utcnow

---

thoth/slo_reporter/sli_thoth_services/sli_kebechet.py

Adjust description

---

thoth/slo_reporter/sli_apis/sli_user_api.py
thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
thoth/slo_reporter/sli_learning/sli_learning.py
thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py
thoth/slo_reporter/sli_thoth_services/sli_kebechet.py

Fixes: https://github.com/thoth-station/slo-reporter/issues/139

check for DRY_RUN

---

thoth/slo_reporter/sli_report.py

Add environment to email title to avoid confusion

---

.aicoe-ci.yaml
.thoth.yaml
Pipfile.lock

Related-To: https://github.com/thoth-station/thoth-application/issues/545

port to python 38

---

app.py

Fixes: https://github.com/thoth-station/slo-reporter/issues/160
Opened feature request upstream: https://github.com/AICoE/prometheus-api-client-python/issues/180, 
https://github.com/AICoE/prometheus-api-client-python/pull/181

Add check for Thanos availability before starting to acquire metrics.

---

thoth/slo_reporter/sli_apis/sli_user_api.py
thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
thoth/slo_reporter/sli_learning/sli_learning.py
thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py
thoth/slo_reporter/sli_thoth_services/sli_kebechet.py

Fixes: https://github.com/thoth-station/slo-reporter/issues/161

Adjust metrics due to changes on Prometheus side

---

thoth/slo_reporter/static/templates/pypi_knowledge_graph.html

Change column name in template to be more explicit

---

thoth/slo_reporter/sli_report.py
thoth/slo_reporter/static/templates/intro.html

From `Thoth SLI Metrics Report (stage environment) from 2021-01-21 to 2021-01-22.`
to `Thoth SLI Metrics Report (stage environment) on day 2021-01-22.`

Correct title email

---

app.py
thoth/slo_reporter/utils.py

Fixes: https://github.com/thoth-station/slo-reporter/issues/188

Introduce check on data retrieval from ceph

---

thoth/slo_reporter/configuration.py

Fixes: https://github.com/thoth-station/metrics-exporter/issues/581

Add build analysis in the report sent by email

---

thoth/slo_reporter/configuration.py

Add defaults

---

.pre-commit-config.yaml
OWNERS
app.py
thoth/slo_reporter/sli_references.py
thoth/slo_reporter/sli_report.py
thoth/slo_reporter/static/templates/thoth_base_images.html
thoth/slo_reporter/static/templates/thoth_hardware.html
thoth/slo_reporter/static/templates/thoth_recommendations.html
thoth/slo_reporter/static/templates/thoth_solvers.html

some minor wording changes

---

thoth/slo_reporter/sli_thoth_adviser_inputs/sli_thoth_hardware.py
thoth/slo_reporter/static/templates/thoth_integrations.html

Minor adjustments

---

.gitignore
thoth/slo_reporter/SLO-reporter.html
thoth/slo_reporter/sli_thoth_adviser_outputs/sli_thoth_adviser_justifications_errors.py
thoth/slo_reporter/utils.py

Fix issue on datatype

---

README.md

Related-To: https://github.com/thoth-station/slo-reporter/issues/250

Add link html preview to README to easily discover status

---

thoth/slo_reporter/sli_references.py

Fix Description of the reference in the report

---

.github/ISSUE_TEMPLATE/kebechet_info.md
.github/ISSUE_TEMPLATE/kebechet_update.md
.github/ISSUE_TEMPLATE/redeliver_container_image.md

Add standard GitHub templates

---

README.md
thoth/slo_reporter/configuration.py
thoth/slo_reporter/sli_thoth_adviser_inputs/README.md

Related-To: https://github.com/thoth-station/user-api/issues/1454

Remove qeb-hwt bits

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.pre-commit-config.yaml
.prow.yaml
thoth/slo_reporter/sli_apis/sli_user_api.py
thoth/slo_reporter/sli_backends/sli_workflow_latency.py
thoth/slo_reporter/sli_backends/sli_workflow_quality.py
thoth/slo_reporter/sli_backends/sli_workflow_task_latency.py
thoth/slo_reporter/sli_backends/sli_workflow_task_quality.py
thoth/slo_reporter/sli_base.py
thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
thoth/slo_reporter/sli_learning/sli_learning.py
thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py
thoth/slo_reporter/sli_thoth_adviser_inputs/sli_thoth_base_image.py
thoth/slo_reporter/sli_thoth_adviser_inputs/sli_thoth_hardware.py
thoth/slo_reporter/sli_thoth_adviser_inputs/sli_thoth_integration.py
thoth/slo_reporter/sli_thoth_adviser_inputs/sli_thoth_integration_users.py
thoth/slo_reporter/sli_thoth_adviser_inputs/sli_thoth_recommendation_type.py
thoth/slo_reporter/sli_thoth_adviser_inputs/sli_thoth_solver.py
thoth/slo_reporter/sli_thoth_adviser_outputs/sli_thoth_adviser_justifications_errors.py
thoth/slo_reporter/sli_thoth_adviser_outputs/sli_thoth_adviser_reports_statistics.py
thoth/slo_reporter/sli_thoth_services/sli_kebechet.py
thoth/slo_reporter/utils.py

this is a cherry pick of https://github.com/thoth-station/template-project/commit/0c17cf39f4de9509d587d40c9d90f6bbc8fa5a0f

updates from the template project

---

Pipfile.lock
thoth/slo_reporter/configuration.py
thoth/slo_reporter/sli_thoth_adviser_inputs/sli_thoth_integration_users.py
thoth/slo_reporter/static/templates/start.html

Fixes: https://github.com/thoth-station/slo-reporter/issues/295

Fix integration enum

---

thoth/slo_reporter/configuration.py

Generalize metric

---

.pre-commit-config.yaml
.prow.yaml
app.py
pyproject.toml
thoth/slo_reporter/configuration.py
thoth/slo_reporter/sli_apis/sli_user_api.py
thoth/slo_reporter/sli_backends/sli_workflow_latency.py
thoth/slo_reporter/sli_backends/sli_workflow_quality.py
thoth/slo_reporter/sli_backends/sli_workflow_task_latency.py
thoth/slo_reporter/sli_backends/sli_workflow_task_quality.py
thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
thoth/slo_reporter/sli_learning/sli_learning.py
thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py
thoth/slo_reporter/sli_references.py
thoth/slo_reporter/sli_thoth_adviser_inputs/sli_thoth_integration_users.py
thoth/slo_reporter/sli_thoth_adviser_outputs/sli_thoth_adviser_justifications_errors.py
thoth/slo_reporter/sli_thoth_services/sli_kebechet.py

Related-To: https://github.com/thoth-station/thoth-application/pull/2175

Update labels for queries for new monitoring

---

thoth/slo_reporter/configuration.py

Adjust env variable deployment to distinguish between smaug-prod and aws-prod
